# Generated by Django 5.1.2 on 2024-10-31 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_product_stock_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
