# Generated by Django 5.1.2 on 2024-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_city_order_delivery_address_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
